apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dev
  namespace:  dev
spec:
  selector:
    matchLabels:
      app:  dev

  replicas: 1
  template:
    metadata:
      labels:
        app:  dev

    spec:
      containers:
        - name: app
          image: ghcr.io/imranqutab/go-app:latest
          ports:
            - containerPort: 6500
      imagePullSecrets:
      - name: 
# appname:  dev
